name: CI-CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id:
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIP_PROVIDER_NAME }}
          service_account: ${{ secrets.APPENGINE_SA_EMAIL }}

      - name: Deploy to Google AppEngine
        id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          working_directory: backend
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: show output
          run: echo ${{ steps.deploy.outputs.url }}
