name: CI-CD

on:
  push:
    branches: [main]

jobs:
  backend:
    name: Backend

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Linter
        run: |
          cd backend
          yarn install
          yarn lint

      - name: Build
        run: |
          cd backend
          yarn install
          yarn build

      - name: Test
        run: |
          cd backend
          yarn install
          yarn test

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.APPENGINE_SA_EMAIL }}

      # - name: Gcloud
      #   id: gcloud
      #   run: |-
      #     gcloud auth login --brief --quiet --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      #     gcloud services list

      #  TODO: deploy
      # - name: Deploy to Google AppEngine
      #   id: deploy
      #   uses: google-github-actions/deploy-appengine@v1
      #   with:
      #     working_directory: backend
      #     deliverables: app.yaml
      #     project_id: ${{ secrets.GCP_PROJECT }}

      # - name: show output
      #   run: echo "${{ steps.deploy.outputs.url }}"

  frontend:
    name: Frontend

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd frontend
          yarn install
          yarn build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: frontend/dist
